"""
E2E test for migration 1.0.0a35 (drop stale release-X.Y.Z.sql).

A release schema generated before the a33 metadata->data switch holds no
application data, so restoring from it leaves development databases
empty. Those files live on release branches (and on the patch branches
that inherit them), never on ho-prod, and .hop/ syncing propagates
additions but never deletions - so the migration has to visit each
branch itself.

This verifies the end-to-end behaviour on a real repository:
  - stale release schemas are removed on the release branch AND on the
    patch branch that inherited a copy
  - ho-prod, where the file never existed, is left alone
  - a project with no model/metadata-*.sql (i.e. one that never used the
    old mechanism) keeps its release schemas untouched
"""
import re
import pytest


def _downgrade_hop_version(run, project_dir, old_version):
    """Write old_version into .hop/config on ho-prod, commit and push."""
    run(['git', 'checkout', 'ho-prod'])
    config_path = project_dir / '.hop' / 'config'
    content = config_path.read_text()
    content = re.sub(r'(hop_version\s*=\s*)\S+', rf'\g<1>{old_version}', content)
    config_path.write_text(content)
    run(['git', 'add', str(config_path)])
    run(['git', 'commit', '--no-verify', '-m', f'test: downgrade to {old_version}'])
    run(['git', 'push', '--no-verify', 'origin', 'ho-prod'])


def _add_legacy_metadata_file(run, project_dir):
    """Mark the project as predating a33 by leaving a metadata-*.sql behind."""
    run(['git', 'checkout', 'ho-prod'])
    legacy = project_dir / '.hop' / 'model' / 'metadata-0.0.0.sql'
    legacy.write_text(
        "COPY half_orm_meta.hop_release "
        "(major, minor, patch, pre_release, pre_release_num) FROM stdin;\n"
        "0\t0\t0\t\t\n"
        "\\.\n"
    )
    run(['git', 'add', str(legacy)])
    run(['git', 'commit', '--no-verify', '-m', 'test: legacy metadata file'])
    run(['git', 'push', '--no-verify', 'origin', 'ho-prod'])


def _file_on_branch(run, branch, relative_path):
    """True when relative_path is tracked on branch."""
    result = run(
        ['git', 'ls-tree', '-r', '--name-only', branch, relative_path],
        check=False,
    )
    return bool(result.stdout.strip())


@pytest.mark.e2e
class TestMigrationDropsStaleReleaseSchemas:
    """Migration 1.0.0a35 cleans release schemas across active branches."""

    def test_removes_stale_release_schema_on_release_and_patch_branches(
        self, project_with_release, old_hop_version
    ):
        """Stale release schema is deleted wherever it is carried."""
        env = project_with_release
        run = env['run']
        project_dir = env['project_dir']
        version = env['release_version']
        release_branch = f'ho-release/{version}'
        release_schema = f'.hop/model/release-{version}.sql'

        # A patch branch inherits the release schema from the release branch.
        patch_id = '1-inherits-release-schema'
        run(['half_orm', 'dev', 'patch', 'create', patch_id])
        patch_branch = f'ho-patch/{patch_id}'

        assert _file_on_branch(run, release_branch, release_schema), (
            "precondition: release branch must carry the release schema"
        )
        assert _file_on_branch(run, patch_branch, release_schema), (
            "precondition: patch branch must have inherited the release schema"
        )

        _add_legacy_metadata_file(run, project_dir)
        _downgrade_hop_version(run, project_dir, old_hop_version)

        result = run(['half_orm', 'dev', 'migrate'], input_text='y\n', check=False)
        assert result.returncode == 0, (
            f"migrate should succeed.\n"
            f"STDOUT: {result.stdout}\nSTDERR: {result.stderr}"
        )

        assert not _file_on_branch(run, release_branch, release_schema), (
            f"stale {release_schema} should be gone from {release_branch}"
        )
        assert not _file_on_branch(run, patch_branch, release_schema), (
            f"stale {release_schema} should be gone from {patch_branch}"
        )

    def test_leaves_release_schema_alone_without_legacy_metadata(
        self, project_with_release, old_hop_version
    ):
        """A project that never used metadata-*.sql keeps its release schemas.

        Its release schemas were generated by the current mechanism and
        already carry the full data - rebuilding them would be pointless
        work.
        """
        env = project_with_release
        run = env['run']
        project_dir = env['project_dir']
        version = env['release_version']
        release_branch = f'ho-release/{version}'
        release_schema = f'.hop/model/release-{version}.sql'

        # No legacy metadata-*.sql is created here.
        _downgrade_hop_version(run, project_dir, old_hop_version)

        result = run(['half_orm', 'dev', 'migrate'], input_text='y\n', check=False)
        assert result.returncode == 0, (
            f"migrate should succeed.\n"
            f"STDOUT: {result.stdout}\nSTDERR: {result.stderr}"
        )

        assert _file_on_branch(run, release_branch, release_schema), (
            f"{release_schema} must be preserved when the project never had "
            f"metadata-*.sql"
        )
