"""
Migration: Regenerate auto-generated relation test files.

This migration:
- Finds all test files marked "DO NOT EDIT" (auto-generated by hop)
- Regenerates them with the updated template which adds:
  * from half_orm.relation import Relation
  * async test_fkeys(): validates FK aliases against _ho_fkeys and
    calls ho_acount() to verify async access end-to-end

Files modified by the developer (without "DO NOT EDIT") are left untouched.
"""

import re
from pathlib import Path


def get_description():
    """Return migration description."""
    return "Regenerate auto-generated relation test files (async test_fkeys)"


_FROM_RE = re.compile(r'^from (\S+) import (\S+)', re.MULTILINE)


def migrate(repo):
    """Execute migration: regenerate auto-generated relation test files."""
    import os
    import click
    from half_orm_dev.utils import TEMPLATE_DIRS
    from half_orm import utils as ho_utils

    base_dir = Path(repo.base_dir)
    tests_dir = base_dir / 'tests'

    if not tests_dir.exists():
        print("  ⚠️  tests/ directory not found, skipping.")
        return

    candidates = [
        p for p in tests_dir.rglob('test_*.py')
        if 'DO NOT EDIT' in p.read_text()
    ]

    if not candidates:
        print("  ✓ No auto-generated relation test files found.")
        return

    already_updated = [p for p in candidates if 'test_fkeys' in p.read_text() and 'async' in p.read_text()]
    to_update = [p for p in candidates if p not in already_updated]

    if not to_update:
        print(f"  ✓ All {len(candidates)} relation test file(s) already up-to-date.")
        return

    if not click.confirm(
        f"  Regenerate {len(to_update)} relation test file(s) "
        f"({len(already_updated)} already up-to-date)?",
        default=True
    ):
        return

    template = ho_utils.read(os.path.join(TEMPLATE_DIRS, 'relation_test'))

    updated = 0
    skipped = 0
    for test_path in sorted(to_update):
        content = test_path.read_text()
        m = _FROM_RE.search(content)
        if not m:
            print(f"  ⚠️  Could not parse module/class from {test_path.name}, skipping.")
            skipped += 1
            continue

        module, class_name = m.group(1), m.group(2)
        test_path.write_text(template.format(module=module, class_name=class_name))
        repo.hgit.add(str(test_path))
        updated += 1

    print(f"  ✓ Regenerated {updated} file(s){f', {skipped} skipped' if skipped else ''}.")
